"""empty message

Revision ID: 1902046b3184
Revises: 6e8bf2e6e586
Create Date: 2020-03-29 21:01:57.120605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1902046b3184'
down_revision = '6e8bf2e6e586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('s_phone', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'student', ['s_phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_column('student', 's_phone')
    # ### end Alembic commands ###
