"""empty message

Revision ID: 6e8bf2e6e586
Revises: f22f005276e5
Create Date: 2020-03-29 17:03:12.315405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e8bf2e6e586'
down_revision = 'f22f005276e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('_s_password', sa.String(length=256), nullable=True))
    op.drop_column('student', 's_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('s_password', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('student', '_s_password')
    # ### end Alembic commands ###
